"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "hi" | "bn" | "ta" | "te" | "kn" | "mr" | "gu" | "pa" | "ml" | "as";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LANGUAGES: { code: Language; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "mr", label: "Marathi", native: "ಮರಾઠી" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી" },
  { code: "pa", label: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ml", label: "Malayalam", native: "മലയാളം" },
  { code: "as", label: "Assamese", native: "অসমীয়া" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    NAV_HOME: "Home",
    NAV_ANALYZE: "Search",
    NAV_CART: "Cart",
    NAV_INSIGHTS: "Insights",
    NAV_PROFILE: "Profile",
    NAV_INBOX: "Inbox",
    NAV_LOGOUT: "Logout",
    WELCOME_TITLE: "Welcome to NutriSaathi AI",
    WELCOME_SUBTITLE: "Your personal food intelligence companion.",
    WELCOME_WHAT_LABEL: "What is NutriSaathi?",
    WELCOME_WHAT_DESC: "NutriSaathi analyzes Indian dishes, snacks, and global brands to give you instant health scores and smarter alternatives based on your regional food culture.",
    WELCOME_HOW_LABEL: "How to use",
    WELCOME_STEP1: "Search for any dish, brand, or grocery item.",
    WELCOME_STEP2: "Get an instant health score (0-100) and risk assessment.",
    WELCOME_STEP3: "See smarter, regional swaps to stay healthy.",
    WELCOME_EXAMPLES_LABEL: "Try these examples",
    WELCOME_START_BTN: "Start Testing",
    SEARCH_TITLE: "NutriSaathi AI",
    SEARCH_DESC: "Know exactly what's in your food.",
    SEARCH_PLACEHOLDER: "Search dishes (e.g. Samosa, Oats...)",
    SEARCH_ANALYZE_BTN: "Analyze",
    SEARCH_HISTORY_LABEL: "Recent",
    RESULT_HEALTH_SCORE: "Health Score",
    RESULT_VERDICT: "The Verdict",
    RESULT_DECISION: "Decision",
    RESULT_QUANTITY: "Safe Quantity",
    RESULT_ALTERNATIVES: "Better Alternatives",
    RESULT_REASON: "Reason",
    RESULT_LOGIC: "Logic",
    RESULT_RISK: "Warnings",
    CART_TITLE: "Basket Intelligence",
    CART_DESC: "Audit your grocery list.",
    CART_ITEMS_LABEL: "My Basket",
    CART_SWAPS_LABEL: "Smart Grocery Swaps",
    CART_ANALYZING: "Analyzing...",
    CART_AUDIT_BTN: "Audit Full Basket",
    CART_VERDICT: "The Verdict",
    CART_EMPTY: "Your basket is empty",
    CART_ADD_PLACEHOLDER: "Add grocery item...",
    PROFILE_TITLE: "Health Profile",
    PROFILE_DESC: "Manage your health metrics.",
    VOICE_SEARCH_ERROR: "Voice not recognized, please try again.",
    VOICE_SEARCH_HINT: "Listening...",
    VOICE_OUTPUT_HINT: "Listen to result",
    VOICE_PLAYING: "Speaking...",
  },
  hi: {
    NAV_HOME: "होम",
    NAV_ANALYZE: "सर्च",
    NAV_CART: "टोकरी",
    NAV_INSIGHTS: "आंकड़े",
    NAV_PROFILE: "प्रोफ़ाइल",
    NAV_INBOX: "इनबॉक्स",
    NAV_LOGOUT: "लॉगआउट",
    WELCOME_TITLE: "न्यूट्रिसाथी AI में आपका स्वागत है",
    WELCOME_SUBTITLE: "आपका व्यक्तिगत भोजन खुफिया साथी।",
    WELCOME_WHAT_LABEL: "न्यूट्रिसाथी क्या है?",
    WELCOME_WHAT_DESC: "न्यूट्रिसाथी भारतीय व्यंजनों, स्नैक्स और वैश्विक ब्रांडों का विश्लेषण करता है ताकि आपको आपकी क्षेत्रीय खाद्य संस्कृति के आधार पर तत्काल स्वास्थ्य स्कोर और बेहतर विकल्प मिल सकें।",
    WELCOME_HOW_LABEL: "कैसे इस्तेमाल करें",
    WELCOME_STEP1: "किसी भी डिश, ब्रांड या ग्रोसरी आइटम को खोजें।",
    WELCOME_STEP2: "तत्काल स्वास्थ्य स्कोर (0-100) और जोखिम मूल्यांकन प्राप्त करें।",
    WELCOME_STEP3: "स्वस्थ रहने के लिए स्मार्ट, क्षेत्रीय विकल्प देखें।",
    WELCOME_EXAMPLES_LABEL: "इन उदाहरणों को आजमाएं",
    WELCOME_START_BTN: "टेस्टिंग शुरू करें",
    SEARCH_TITLE: "न्यूट्रिसाथी AI",
    SEARCH_DESC: "जानें आपके भोजन में क्या है।",
    SEARCH_PLACEHOLDER: "खाना खोजें (जैसे समोसा, ओट्स...)",
    SEARCH_ANALYZE_BTN: "जांचें",
    SEARCH_HISTORY_LABEL: "हाल के",
    RESULT_HEALTH_SCORE: "स्वास्थ्य स्कोर",
    RESULT_VERDICT: "निष्कर्ष",
    RESULT_DECISION: "फैसला",
    RESULT_QUANTITY: "सुरक्षित मात्रा",
    RESULT_ALTERNATIVES: "बेहतर विकल्प",
    RESULT_REASON: "कारण",
    RESULT_LOGIC: "तर्क",
    RESULT_RISK: "चेतावनी",
    CART_TITLE: "बास्केट ऑडिट",
    CART_DESC: "ग्रोसरी लिस्ट की जांच करें।",
    CART_ITEMS_LABEL: "मेरी टोकरी",
    CART_SWAPS_LABEL: "स्मार्ट स्वैप",
    CART_ANALYZING: "विश्लेषण हो रहा है...",
    CART_AUDIT_BTN: "पूरी टोकरी की जांच करें",
    CART_VERDICT: "निष्कर्ष",
    CART_EMPTY: "आपकी टोकरी खाली है",
    CART_ADD_PLACEHOLDER: "ग्रोसरी आइटम जोड़ें...",
    PROFILE_TITLE: "स्वास्थ्य प्रोफ़ाइल",
    PROFILE_DESC: "अपनी जानकारी अपडेट करें।",
    VOICE_SEARCH_ERROR: "आवाज समझ नहीं आई, कृपया फिर से कोशिश करें।",
    VOICE_SEARCH_HINT: "सुन रहे हैं...",
    VOICE_OUTPUT_HINT: "निष्कर्ष सुनें",
    VOICE_PLAYING: "बोल रहे हैं...",
  },
  bn: {
    NAV_HOME: "হোম",
    NAV_ANALYZE: "সার্চ",
    NAV_CART: "কার্ট",
    NAV_INSIGHTS: "ইনসাইটস",
    NAV_PROFILE: "প্রোফাইল",
    NAV_INBOX: "ইনবক্স",
    NAV_LOGOUT: "লগআউট",
    WELCOME_TITLE: "নিউট্রিসাথি AI-তে স্বাগতম",
    WELCOME_SUBTITLE: "আপনার ব্যক্তিগত খাদ্য বুদ্ধিমত্তা সঙ্গী।",
    WELCOME_WHAT_LABEL: "নিউট্রিসাথি কী?",
    WELCOME_WHAT_DESC: "নিউট্রিসাথি ভারতীয় খাবার, স্ন্যাকস এবং বৈশ্বিক ব্র্যান্ডগুলি বিশ্লেষণ করে আপনাকে তাৎক্ষণিক স্বাস্থ্য স্কোর এবং আপনার আঞ্চলিক খাদ্য সংস্কৃতির উপর ভিত্তি করে স্মার্ট বিকল্প সরবরাহ করে।",
    WELCOME_HOW_LABEL: "কিভাবে ব্যবহার করবেন",
    WELCOME_STEP1: "যেকোনো খাবার, ব্র্যান্ড বা মুদি সামগ্রী অনুসন্ধান করুন।",
    WELCOME_STEP2: "তাৎক্ষণিক স্বাস্থ্য স্কোর (০-১০০) এবং ঝুঁকি মূল্যায়ন পান।",
    WELCOME_STEP3: "সুস্থ থাকতে স্মার্ট, আঞ্চলিক বিকল্পগুলি দেখুন।",
    WELCOME_EXAMPLES_LABEL: "এই উদাহরণগুলো চেষ্টা করুন",
    WELCOME_START_BTN: "টেস্টিং শুরু করুন",
    SEARCH_TITLE: "নিউট্রিসাথি AI",
    SEARCH_DESC: "আপনার খাবারে কী আছে জানুন।",
    SEARCH_PLACEHOLDER: "খাবার খুঁজুন (যেমন সমোসা, ওটস...)",
    SEARCH_ANALYZE_BTN: "বিশ্লেষণ করুন",
    SEARCH_HISTORY_LABEL: "সাম্প্রতিক",
    RESULT_HEALTH_SCORE: "স্বাস্থ্য স্কোর",
    RESULT_VERDICT: "রায়",
    RESULT_DECISION: "সিদ্ধান্ত",
    RESULT_QUANTITY: "নিরাপদ পরিমাণ",
    RESULT_ALTERNATIVES: "স্মার্ট বিকল্প",
    RESULT_REASON: "কারণ",
    RESULT_LOGIC: "যুক্তি",
    RESULT_RISK: "সতর্কতা",
    CART_TITLE: "বাস্কেট অডিট",
    CART_DESC: "মুদি তালিকার পরীক্ষা।",
    CART_ITEMS_LABEL: "আমার বাস্কেট",
    CART_SWAPS_LABEL: "স্মার্ট সোয়াপস",
    CART_ANALYZING: "বিশ্লেষণ করা হচ্ছে...",
    CART_AUDIT_BTN: "পুরো বাস্কেট অডিট করুন",
    CART_VERDICT: "রায়",
    CART_EMPTY: "আপনার বাস্কেট খালি",
    CART_ADD_PLACEHOLDER: "মুদি সামগ্রী যোগ করুন...",
    PROFILE_TITLE: "স্বাস্থ্য প্রোফাইল",
    PROFILE_DESC: "আপনার তথ্য পরিচালনা করুন।",
    VOICE_SEARCH_ERROR: "কণ্ঠস্বর বোঝা যায়নি, অনুগ্রহ করে আবার চেষ্টা করুন।",
    VOICE_SEARCH_HINT: "শুনছি...",
    VOICE_OUTPUT_HINT: "রায় শুনুন",
    VOICE_PLAYING: "কথা বলছি...",
  },
  ta: {
    NAV_HOME: "முகப்பு",
    NAV_ANALYZE: "தேடல்",
    NAV_CART: "கூடை",
    NAV_INSIGHTS: "நுண்ணறிவு",
    NAV_PROFILE: "சுயவிவரம்",
    NAV_INBOX: "பெட்டி",
    NAV_LOGOUT: "வெளியேறு",
    WELCOME_TITLE: "நியூட்ரிசாதி AI-க்கு வரவேற்கிறோம்",
    WELCOME_SUBTITLE: "உங்களின் தனிப்பட்ட உணவு நுண்ணறிவுத் துணை.",
    WELCOME_WHAT_LABEL: "நியூட்ரிசாதி என்றால் என்ன?",
    WELCOME_WHAT_DESC: "நியூட்ரிசாதி இந்திய உணவுகள், தின்பண்டங்கள் மற்றும் உலகளாவிய பிராண்டுகளை ஆராய்ந்து, உங்கள் பிராந்திய உணவு கலாச்சாரத்தின் அடிப்படையில் உடனடி ஆரோக்கிய மதிப்பெண்களையும் சிறந்த மாற்றுகளையும் வழங்குகிறது.",
    WELCOME_HOW_LABEL: "எப்படி பயன்படுத்துவது",
    WELCOME_STEP1: "ஏதேனும் உணவு, பிராண்ட் அல்லது மளிகை பொருளைத் தேடுங்கள்.",
    WELCOME_STEP2: "உடனடி ஆரோக்கிய மதிப்பெண் (0-100) மற்றும் அபாய மதிப்பீட்டைப் பெறுங்கள்.",
    WELCOME_STEP3: "ஆரோக்கியமாக இருக்க சிறந்த மாற்றுகளைக் காண்க.",
    WELCOME_EXAMPLES_LABEL: "இந்த உதாரணங்களை முயற்சிக்கவும்",
    WELCOME_START_BTN: "சோதனையைத் தொடங்கு",
    SEARCH_TITLE: "நியூட்ரிசாதி AI",
    SEARCH_DESC: "உணவில் என்ன உள்ளது எனத் தெரிந்துகொள்ளுங்கள்.",
    SEARCH_PLACEHOLDER: "உணவைத் தேடுங்கள்...",
    SEARCH_ANALYZE_BTN: "ஆராய்",
    SEARCH_HISTORY_LABEL: "சமீபத்திய",
    RESULT_HEALTH_SCORE: "ஆரோக்கிய மதிப்பெண்",
    RESULT_VERDICT: "தீர்ப்பு",
    RESULT_DECISION: "முடிவு",
    RESULT_QUANTITY: "பாதுகாப்பான அளவு",
    RESULT_ALTERNATIVES: "சிறந்த மாற்றுகள்",
    RESULT_REASON: "காரணம்",
    RESULT_LOGIC: "தர்க்கம்",
    RESULT_RISK: "எச்சரிக்கைகள்",
    CART_TITLE: "கூடை ஆய்வு",
    CART_DESC: "மளிகைப் பட்டியலைச் சரிபார்க்கவும்.",
    CART_ITEMS_LABEL: "எனது கூடை",
    CART_SWAPS_LABEL: "ஆரோக்கிய மாற்றுகள்",
    CART_ANALYZING: "ஆராய்கிறது...",
    CART_AUDIT_BTN: "முழு கூடையை ஆய்வு செய்",
    CART_VERDICT: "தீர்ப்பு",
    CART_EMPTY: "உங்கள் கூடை காலியாக உள்ளது",
    CART_ADD_PLACEHOLDER: "உணவுப் பொருளைச் சேர்க்கவும்...",
    PROFILE_TITLE: "ஆரோக்கிய சுயவிவரம்",
    PROFILE_DESC: "சுயவிவரத்தை நிர்வகிக்கவும்.",
    VOICE_SEARCH_ERROR: "குரல் அடையாளம் காணப்படவில்லை, மீண்டும் முயற்சிக்கவும்.",
    VOICE_SEARCH_HINT: "கேட்கிறது...",
    VOICE_OUTPUT_HINT: "தீர்ப்பைக் கேளுங்கள்",
    VOICE_PLAYING: "பேசுகிறோம்...",
  },
  te: {
    NAV_HOME: "హోమ్",
    NAV_ANALYZE: "వెతకండి",
    NAV_CART: "కార్ట్",
    NAV_INSIGHTS: "అవగాహన",
    NAV_PROFILE: "ప్రొఫైల్",
    NAV_INBOX: "ఇన్బాక్స్",
    NAV_LOGOUT: "లాగౌట్",
    WELCOME_TITLE: "న్యూట్రిసాథి AIకి స్వాగతం",
    WELCOME_SUBTITLE: "మీ వ్యక్తిగత ఆహార అవగాహన భాగస్వామి.",
    WELCOME_WHAT_LABEL: "న్యూట్రిసాథి అంటే ఏమిటి?",
    WELCOME_WHAT_DESC: "న్యూట్రిసాథి భారతీయ వంటకాలు, స్నాక్స్ మరియు అంతర్జాతీయ బ్రాండ్‌లను విశ్లేషించి, మీ ప్రాంతీయ ఆహార సంస్కృతి ఆధారంగా తక్షణ ఆరోగ్య స్కోర్లు మరియు మెరుగైన ప్రత్యామ్నాయాలను అందిస్తుంది.",
    WELCOME_HOW_LABEL: "ఎలా ఉపయోగించాలి",
    WELCOME_STEP1: "ఏదైనా వంటకం, బ్రాండ్ లేదా కిరాణా వస్తువు కోసం వెతకండి.",
    WELCOME_STEP2: "తక్షణ ఆరోగ్య స్కోర్ (0-100) మరియు రిస్క్ అసెస్‌మెంట్‌ను పొందండి.",
    WELCOME_STEP3: "ఆరోగ్యంగా ఉండటానికి మెరుగైన ప్రత్యామ్నాయాలను చూడండి.",
    WELCOME_EXAMPLES_LABEL: "ఈ ఉదాహరణలను ప్రయత్నించండి",
    WELCOME_START_BTN: "పరీక్ష ప్రారంభించండి",
    SEARCH_TITLE: "న్యూట్రిసాథి AI",
    SEARCH_DESC: "మీ ఆహారంలో ఏముందో తెలుసుకోండి.",
    SEARCH_PLACEHOLDER: "ఆహారం కోసం వెతకండి...",
    SEARCH_ANALYZE_BTN: "విశ్లేషించు",
    SEARCH_HISTORY_LABEL: "ఇటీవలి",
    RESULT_HEALTH_SCORE: "ఆరోగ్య స్కోర్",
    RESULT_VERDICT: "తీర్పు",
    RESULT_DECISION: "తీర్పు",
    RESULT_QUANTITY: "సురక్షిత పరిమాణం",
    RESULT_ALTERNATIVES: "ప్రత్యామ్నాయాలు",
    RESULT_REASON: "కారణం",
    RESULT_LOGIC: "తర్కం",
    RESULT_RISK: "హెచ్చరికలు",
    CART_TITLE: "బాస్కెట్ విశ్లేషణ",
    CART_DESC: "మీ కిరాణా జాబితాను తనిఖీ చేయండి.",
    CART_ITEMS_LABEL: "నా బాస్కెట్",
    CART_SWAPS_LABEL: "ఆరోగ్య ప్రత్యామ్నాయాలు",
    CART_ANALYZING: "విశ్లేషిస్తోంది...",
    CART_AUDIT_BTN: "బాస్కెట్ అంతా తనిఖీ చేయండి",
    CART_VERDICT: "తీర్పు",
    CART_EMPTY: "మీ బాస్కెట్ ఖాళీగా ఉంది",
    CART_ADD_PLACEHOLDER: "వస్తువును జోడించండి...",
    PROFILE_TITLE: "ఆరోగ్య ప్రొఫైల్",
    PROFILE_DESC: "మీ వివరాలను నిర్వహించండి.",
    VOICE_SEARCH_ERROR: "వాయిస్ గుర్తించబడలేదు, దయచేసి మళ్ళీ ప్రయత్నించండి.",
    VOICE_SEARCH_HINT: "వింటున్నాము...",
    VOICE_OUTPUT_HINT: "తీర్పు వినండి",
    VOICE_PLAYING: "మాట్లాడుతున్నాము...",
  },
  kn: {
    NAV_HOME: "ಮುಖಪುಟ",
    NAV_ANALYZE: "ಹುಡುಕು",
    NAV_CART: "ಕಾರ್ಟ್",
    NAV_INSIGHTS: "ಒಳನೋಟಗಳು",
    NAV_PROFILE: "ಪ್ರೊಫೈಲ್",
    NAV_INBOX: "ಇನ್ಬಾಕ್ಸ್",
    NAV_LOGOUT: "ಲಾಗೌಟ್",
    WELCOME_TITLE: "ನ್ಯೂಟ್ರಿಸಾಥಿ AI ಗೆ ಸುಸ್ವಾಗತ",
    WELCOME_SUBTITLE: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಆಹಾರ ಬುದ್ಧಿವಂತಿಕೆಯ ಸಂಗಾತಿ.",
    WELCOME_WHAT_LABEL: "ನ್ಯೂಟ್ರಿಸಾಥಿ ಎಂದರೇನು?",
    WELCOME_WHAT_DESC: "ನ್ಯೂಟ್ರಿಸಾಥಿ ಭಾರತೀಯ ಭಕ್ಷ್ಯಗಳು, ಸ್ನಾಕ್ಸ್ ಮತ್ತು ಜಾಗತಿಕ ಬ್ರಾಂಡ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ನಿಮ್ಮ ಪ್ರಾದೇಶಿಕ ಆಹಾರ ಸಂಸ್ಕೃತಿಯ ಆಧಾರದ ಮೇಲೆ ತಕ್ಷಣದ ಆರೋಗ್ಯ ಸ್ಕೋರ್‌ಗಳು ಮತ್ತು ಪರ್ಯಾಯಗಳನ್ನು ನೀಡುತ್ತದೆ.",
    WELCOME_HOW_LABEL: "ಬಳಸುವುದು ಹೇಗೆ",
    WELCOME_STEP1: "ಯಾವುದೇ ಖಾದ್ಯ, ಬ್ರಾಂಡ್ ಅಥವಾ ಕಿರಾಣಿ ವಸ್ತುವನ್ನು ಹುಡುಕಿ.",
    WELCOME_STEP2: "ತಕ್ಷಣದ ಆರೋಗ್ಯ ಸ್ಕೋರ್ (0-100) ಮತ್ತು ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ ಪಡೆಯಿರಿ.",
    WELCOME_STEP3: "ಆರೋಗ್ಯವಾಗಿರಲು ಸ್ಮಾರ್ಟ್ ಪರ್ಯಾಯಗಳನ್ನು ನೋಡಿ.",
    WELCOME_EXAMPLES_LABEL: "ಈ ಉದಾಹರಣೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ",
    WELCOME_START_BTN: "ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    SEARCH_TITLE: "ನ್ಯೂಟ್ರಿಸಾಥಿ AI",
    SEARCH_DESC: "ಆಹಾರದಲ್ಲಿ ಏನಿದೆ ಎಂದು ತಿಳಿಯಿರಿ.",
    SEARCH_PLACEHOLDER: "ಆಹಾರವನ್ನು ಹುಡುಕಿ...",
    SEARCH_ANALYZE_BTN: "ವಿಶ್ಲೇಷಿಸು",
    SEARCH_HISTORY_LABEL: "ಇತ್ತೀಚಿನ",
    RESULT_HEALTH_SCORE: "ಆರೋಗ್ಯ ಸ್ಕೋರ್",
    RESULT_VERDICT: "ತೀರ್ಪು",
    RESULT_DECISION: "ತೀರ್ಪು",
    RESULT_QUANTITY: "ಸುರಕ್ಷಿತ ಪ್ರಮಾಣ",
    RESULT_ALTERNATIVES: "ಪರ್ಯಾಯಗಳು",
    RESULT_REASON: "ಕಾರಣ",
    RESULT_LOGIC: "ತರ್ಕ",
    RESULT_RISK: "ಎಚ್ಚರಿಕೆಗಳು",
    CART_TITLE: "ಬಾಸ್ಕೆಟ್ ವಿಶ್ಲೇಷಣೆ",
    CART_DESC: "ನಿಮ್ಮ ಪಟ್ಟಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    CART_ITEMS_LABEL: "ನನ್ನ ಬಾಸ್ಕೆಟ್",
    CART_SWAPS_LABEL: "ಆರೋಗ್ಯ ಪರ್ಯಾಯಗಳು",
    CART_ANALYZING: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    CART_AUDIT_BTN: "ಪೂರ್ಣ ಬಾಸ್ಕೆಟ್ ತಪಾಸಣೆ",
    CART_VERDICT: "ತೀರ್ಪು",
    CART_EMPTY: "ನಿಮ್ಮ ಬಾಸ್ಕೆಟ್ ಖಾಲಿಯಿದೆ",
    CART_ADD_PLACEHOLDER: "ವಸ್ತುವನ್ನು ಸೇರಿಸಿ...",
    PROFILE_TITLE: "ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್",
    PROFILE_DESC: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    VOICE_SEARCH_ERROR: "ಧ್ವನಿ ಗುರುತಿಸಲಾಗಿಲ್ಲ, ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    VOICE_SEARCH_HINT: "ಕೇಳುತ್ತಿದ್ದೇವೆ...",
    VOICE_OUTPUT_HINT: "ತೀರ್ಪನ್ನು ಕೇಳಿ",
    VOICE_PLAYING: "ಮಾತನಾಡುತ್ತಿದ್ದೇವೆ...",
  },
  mr: {
    NAV_HOME: "होम",
    NAV_ANALYZE: "शोध",
    NAV_CART: "कार्ट",
    NAV_INSIGHTS: "अंतर्दृष्टी",
    NAV_PROFILE: "प्रोफाईल",
    NAV_INBOX: "इनबॉक्स",
    NAV_LOGOUT: "लॉगआउट",
    WELCOME_TITLE: "न्यूट्रिसाथी AI मध्ये आपले स्वागत आहे",
    WELCOME_SUBTITLE: "तुमचा वैयक्तिक आहार बुद्धिमत्ता सोबती.",
    WELCOME_WHAT_LABEL: "न्यूट्रिसाथी काय आहे?",
    WELCOME_WHAT_DESC: "न्यूट्रिसाथी भारतीय पदार्थ, स्नॅक्स आणि जागतिक ब्रँड्सचे विश्लेषण करते जेणेकरून तुम्हाला तुमच्या प्रादेशिक अन्न संस्कृतीवर आधारित त्वरित आरोग्य स्कोअर आणि स्मार्ट पर्याय मिळतील.",
    WELCOME_HOW_LABEL: "कसे वापरायचे",
    WELCOME_STEP1: "कोणताही पदार्थ, ब्रँड किंवा किराणा वस्तू शोधा.",
    WELCOME_STEP2: "त्वरित आरोग्य स्कोअर (0-100) आणि जोखीम मूल्यांकन मिळवा.",
    WELCOME_STEP3: "निरोगी राहण्यासाठी स्मार्ट पर्याय पहा.",
    WELCOME_EXAMPLES_LABEL: "ही उदाहरणे वापरून पहा",
    WELCOME_START_BTN: "चाचणी सुरू करा",
    SEARCH_TITLE: "न्यूट्रिसाथी AI",
    SEARCH_DESC: "तुमच्या अन्नात काय आहे ते जाणून घ्या.",
    SEARCH_PLACEHOLDER: "पदार्थ शोधा...",
    SEARCH_ANALYZE_BTN: "विश्लेषण करा",
    SEARCH_HISTORY_LABEL: "अलीकडील",
    RESULT_HEALTH_SCORE: "आरोग्य स्कोअर",
    RESULT_VERDICT: "निकाल",
    RESULT_DECISION: "निकाल",
    RESULT_QUANTITY: "सुरक्षित प्रमाण",
    RESULT_ALTERNATIVES: "स्मार्ट पर्याय",
    RESULT_REASON: "कारण",
    RESULT_LOGIC: "तर्क",
    RESULT_RISK: "सूचना",
    CART_TITLE: "बास्केट ऑडिट",
    CART_DESC: "किराणा यादी तपासा.",
    CART_ITEMS_LABEL: "माझी बास्केट",
    CART_SWAPS_LABEL: "स्मार्ट स्वॅप्स",
    CART_ANALYZING: "विश्लेषण करत आहे...",
    CART_AUDIT_BTN: "संपूर्ण बास्केट तपासा",
    CART_VERDICT: "निकाल",
    CART_EMPTY: "तुमची बास्केट रिकामी आहे",
    CART_ADD_PLACEHOLDER: "वस्तू जोडा...",
    PROFILE_TITLE: "आरोग्य प्रोफाईल",
    PROFILE_DESC: "तुमची माहिती व्यवस्थापित करा.",
    VOICE_SEARCH_ERROR: "आवाज ओळखला नाही, कृपया पुन्हा प्रयत्न करा.",
    VOICE_SEARCH_HINT: "ऐकत आहे...",
    VOICE_OUTPUT_HINT: "निकाल ऐका",
    VOICE_PLAYING: "बोलत आहे...",
  },
  gu: {
    NAV_HOME: "હોમ",
    NAV_ANALYZE: "શોધ",
    NAV_CART: "કાર્ટ",
    NAV_INSIGHTS: "આંતરદૃષ્ટિ",
    NAV_PROFILE: "પ્રોફાઇલ",
    NAV_INBOX: "ઇનબોક્સ",
    NAV_LOGOUT: "લોગઆઉટ",
    WELCOME_TITLE: "ન્યૂટ્રિસાથી AI માં તમારું સ્વાગત છે",
    WELCOME_SUBTITLE: "તમારો વ્યક્તિગત ખોરાક બુદ્ધિમત્તા સાથી.",
    WELCOME_WHAT_LABEL: "ન્યૂટ્રિસાથી શું છે?",
    WELCOME_WHAT_DESC: "ન્યૂટ્રિસાથી ભારતીય વાનગીઓ, નાસ્તા અને વૈશ્વિક બ્રાન્ડ્સનું વિશ્લેષણ કરે છે જેથી તમને તમારી પ્રાદેશિક ખાદ્ય સંસ્કૃતિના આધારે ત્વરિત હેલ્થ સ્કોર અને સ્માર્ટ વિકલ્પો મળી શકે.",
    WELCOME_HOW_LABEL: "કેવી રીતે ઉપયોગ કરવો",
    WELCOME_STEP1: "કોઈપણ વાનગી, બ્રાન્ડ અથવા કરિયાણાની વસ્તુ શોધો.",
    WELCOME_STEP2: "ત્વરિત હેલ્થ સ્કોર (0-100) અને જોખમ મૂલ્યાંકન મેળવો.",
    WELCOME_STEP3: "સ્વસ્થ રહેવા માટે સ્માર્ટ વિકલ્પો જુઓ.",
    WELCOME_EXAMPLES_LABEL: "આ ઉદાહરણો અજમાવો",
    WELCOME_START_BTN: "પરીક્ષણ શરૂ કરો",
    SEARCH_TITLE: "ન્યૂટ્રિસાથી AI",
    SEARCH_DESC: "તમારા ખોરાકમાં શું છે જાણો.",
    SEARCH_PLACEHOLDER: "વાનગી શોધો...",
    SEARCH_ANALYZE_BTN: "વિશ્લેષણ કરો",
    SEARCH_HISTORY_LABEL: "તાજેતરની",
    RESULT_HEALTH_SCORE: "હેલ્થ સ્કોર",
    RESULT_VERDICT: "નિર્ણય",
    RESULT_DECISION: "નિર્ણય",
    RESULT_QUANTITY: "સુરક્ષિત માત્રા",
    RESULT_ALTERNATIVES: "વિકલ્પો",
    RESULT_REASON: "કારણ",
    RESULT_LOGIC: "તર્ક",
    RESULT_RISK: "ચેતવણીઓ",
    CART_TITLE: "બાસ્કેટ ઓડિટ",
    CART_DESC: "યાદીની તપાસ કરો.",
    CART_ITEMS_LABEL: "મારી બાસ્કેટ",
    CART_SWAPS_LABEL: "સ્માર્ટ વિકલ્પો",
    CART_ANALYZING: "વિશ્લેષણ થઈ રહ્યું છે...",
    CART_AUDIT_BTN: "આખી બાસ્કેટ તપાસો",
    CART_VERDICT: "નિર્ણય",
    CART_EMPTY: "તમારી બાસ્કેટ ખાલી છે",
    CART_ADD_PLACEHOLDER: "વસ્તુ ઉમેરો...",
    PROFILE_TITLE: "હેલ્થ પ્રોફાઇલ",
    PROFILE_DESC: "વિગતો મેનેજ કરો.",
    VOICE_SEARCH_ERROR: "અવાજ ઓળખાયો નથી, કૃપા કરીને ફરી પ્રયાસ કરો.",
    VOICE_SEARCH_HINT: "સાંભળી રહ્યા છીએ...",
    VOICE_OUTPUT_HINT: "નિર્ણય સાંભળો",
    VOICE_PLAYING: "બોલી રહ્યા છીએ...",
  },
  pa: {
    NAV_HOME: "ਹੋਮ",
    NAV_ANALYZE: "ਖੋਜ",
    NAV_CART: "ਕਾਰਟ",
    NAV_INSIGHTS: "ਸੂਝ",
    NAV_PROFILE: "ਪ੍ਰੋਫਾਈਲ",
    NAV_INBOX: "ਇਨਬਾਕਸ",
    NAV_LOGOUT: "ਲੌਗਆਉਟ",
    WELCOME_TITLE: "ਨਿਊਟ੍ਰੀਸਾਥੀ AI ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    WELCOME_SUBTITLE: "ਤੁਹਾਡਾ ਨਿੱਜੀ ਭੋਜਨ ਬੁੱਧੀ ਸਾਥੀ।",
    WELCOME_WHAT_LABEL: "ਨਿਊਟ੍ਰੀਸਾਥੀ ਕੀ ਹੈ?",
    WELCOME_WHAT_DESC: "ਨਿਊਟ੍ਰੀਸਾਥੀ ਭਾਰਤੀ ਪਕਵਾਨਾਂ, ਸਨੈਕਸ ਅਤੇ ਗਲੋਬਲ ਬ੍ਰਾਂਡਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ ਤਾਂ ਜੋ ਤੁਹਾਨੂੰ ਤੁਹਾਡੀ ਖੇਤਰੀ ਭੋਜਨ ਸੰਸਕ੍ਰਿਤੀ ਦੇ ਅਧਾਰ ਤੇ ਤੁਰੰਤ ਸਿਹਤ ਸਕੋਰ ਅਤੇ ਸਮਾਰਟ ਵਿਕਲਪ ਮਿਲ ਸਕਣ।",
    WELCOME_HOW_LABEL: "ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ",
    WELCOME_STEP1: "ਕਿਸੇ ਵੀ ਡਿਸ਼, ਬ੍ਰਾਂਡ ਜਾਂ ਕਰਿਆਨੇ ਦੀ ਵਸਤੂ ਦੀ ਖੋਜ ਕਰੋ।",
    WELCOME_STEP2: "ਤੁਰੰਤ ਸਿਹਤ ਸਕੋਰ (0-100) ਅਤੇ ਜੋਖਮ ਮੁਲਾਂਕਣ ਪ੍ਰਾਪਤ ਕਰੋ।",
    WELCOME_STEP3: "ਸਿਹਤਮੰਦ ਰਹਿਣ ਲਈ ਸਮਾਰਟ ਵਿਕਲਪ ਦੇਖੋ।",
    WELCOME_EXAMPLES_LABEL: "ਇਹ ਉਦਾਹਰਣਾਂ ਅਜ਼ਮਾਓ",
    WELCOME_START_BTN: "ਟੈਸਟਿੰਗ ਸ਼ੁਰੂ ਕਰੋ",
    SEARCH_TITLE: "ਨਿਊਟ੍ਰੀਸਾਥੀ AI",
    SEARCH_DESC: "ਜਾਣੋ ਤੁਹਾਡੇ ਭੋਜਨ ਵਿੱਚ ਕੀ ਹੈ।",
    SEARCH_PLACEHOLDER: "ਖਾਣਾ ਲੱਭੋ...",
    SEARCH_ANALYZE_BTN: "ਜਾਂਚ ਕਰੋ",
    SEARCH_HISTORY_LABEL: "ਤਾਜ਼ਾ",
    RESULT_HEALTH_SCORE: "ਸਿਹਤ ਸਕੋਰ",
    RESULT_VERDICT: "ਫੈਸਲਾ",
    RESULT_DECISION: "ਫੈਸਲਾ",
    RESULT_QUANTITY: "ਸੁਰੱਖਿਅਤ ਮਾਤਰਾ",
    RESULT_ALTERNATIVES: "ਬਦਲਾਅ",
    RESULT_REASON: "ਕਾਰਨ",
    RESULT_LOGIC: "ਤਰਕ",
    RESULT_RISK: "ਚੇਤਾਵਨੀਆਂ",
    CART_TITLE: "ਬਾਸਕੇਟ ਜਾਂਚ",
    CART_DESC: "ਲਿਸਟ ਦੀ ਜਾਂਚ ਕਰੋ।",
    CART_ITEMS_LABEL: "ਮੇਰੀ ਬਾਸਕੇਟ",
    CART_SWAPS_LABEL: "ਸਮਾਰਟ ਬਦਲਾਅ",
    CART_ANALYZING: "ਜਾਂਚ ਜਾਰੀ ਹੈ...",
    CART_AUDIT_BTN: "ਪੂਰੀ ਬਾਸਕੇਟ ਦੀ ਜਾਂਚ ਕਰੋ",
    CART_VERDICT: "ਫੈਸਲਾ",
    CART_EMPTY: "ਤੁਹਾਡੀ ਬਾਸਕੇਟ ਖਾਲੀ ਹੈ",
    CART_ADD_PLACEHOLDER: "ਸਮਾਨ ਸ਼ਾਮਲ ਕਰੋ...",
    PROFILE_TITLE: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ",
    PROFILE_DESC: "ਜਾਣਕਾਰੀ ਦਾ ਪ੍ਰਬੰਧ ਕਰੋ।",
    VOICE_SEARCH_ERROR: "ਆਵਾਜ਼ ਦੀ ਪਛਾਣ ਨਹੀਂ ਹੋਈ, ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    VOICE_SEARCH_HINT: "ਸੁਣ ਰਹੇ ਹਾਂ...",
    VOICE_OUTPUT_HINT: "ਫੈਸਲਾ ਸੁਣੋ",
    VOICE_PLAYING: "ਬੋਲ ਰਹੇ ਹਾਂ...",
  },
  ml: {
    NAV_HOME: "ഹോം",
    NAV_ANALYZE: "തിരയുക",
    NAV_CART: "കാർട്ട്",
    NAV_INSIGHTS: "വിവരങ്ങൾ",
    NAV_PROFILE: "പ്രൊഫൈൽ",
    NAV_INBOX: "ഇൻബോക്സ്",
    NAV_LOGOUT: "ലോഗ്ഔട്ട്",
    WELCOME_TITLE: "ന്യൂട്രിസാതി AI-ലേക്ക് സ്വാഗതം",
    WELCOME_SUBTITLE: "നിങ്ങളുടെ വ്യക്തിഗത ഭക്ഷണ ഇന്റലിജൻസ് സഹായി.",
    WELCOME_WHAT_LABEL: "എന്താണ് ന്യൂട്രിസാതി?",
    WELCOME_WHAT_DESC: "ന്യൂട്രിസാതി ഇന്ത്യൻ വിഭവങ്ങൾ, ലഘുഭക്ഷണങ്ങൾ, ആഗോള ബ്രാൻഡുകൾ എന്നിവ വിശകലനം ചെയ്യുകയും നിങ്ങളുടെ പ്രാദേശിക ഭക്ഷണ സംസ്കാരത്തെ അടിസ്ഥാനമാക്കി തൽക്ഷണ ആരോഗ്യ സ്കോറുകളും മികച്ച ബദലുകളും നൽകുകയും ചെയ്യുന്നു.",
    WELCOME_HOW_LABEL: "എങ്ങനെ ഉപയോഗിക്കാം",
    WELCOME_STEP1: "ഏതെങ്കിലും വിഭവം, ബ്രാൻഡ് അല്ലെങ്കിൽ പലചരക്ക് സാധനം തിരയുക.",
    WELCOME_STEP2: "തൽക്ഷണ ആരോഗ്യ സ്കോറും (0-100) അപകടസാധ്യത വിലയിരുത്തലും നേടുക.",
    WELCOME_STEP3: "ആരോഗ്യത്തോടെയിരിക്കാൻ മികച്ച ബദലുകൾ കാണുക.",
    WELCOME_EXAMPLES_LABEL: "ഈ ഉദാഹരണങ്ങൾ പരീക്ഷിക്കുക",
    WELCOME_START_BTN: "പരിശോധന തുടങ്ങാം",
    SEARCH_TITLE: "ന്യൂട്രിസാതി AI",
    SEARCH_DESC: "ഭക്ഷണത്തിൽ എന്താണുള്ളതെന്ന് അറിയുക.",
    SEARCH_PLACEHOLDER: "തിരയുക...",
    SEARCH_ANALYZE_BTN: "പരിശോധിക്കുക",
    SEARCH_HISTORY_LABEL: "അടുത്തകാലത്തെ",
    RESULT_HEALTH_SCORE: "ആരോഗ്യ സ്കോർ",
    RESULT_VERDICT: "വിധി",
    RESULT_DECISION: "തീരുമാനം",
    RESULT_QUANTITY: "സുരക്ഷിതമായ അളവ്",
    RESULT_ALTERNATIVES: "ബദലുകൾ",
    RESULT_REASON: "കാരണം",
    RESULT_LOGIC: "തർക്കം",
    RESULT_RISK: "മുന്നറിയിപ്പുകൾ",
    CART_TITLE: "ബാസ്കറ്റ് ഓഡിറ്റ്",
    CART_DESC: "പട്ടിക പരിശോധിക്കുക.",
    CART_ITEMS_LABEL: "എന്റെ ബാസ്കറ്റ്",
    CART_SWAPS_LABEL: "മാറ്റങ്ങൾ",
    CART_ANALYZING: "പരിശോധിക്കുന്നു...",
    CART_AUDIT_BTN: "മുഴുവൻ ബാസ്കറ്റും പരിശോധിക്കുക",
    CART_VERDICT: "വിധി",
    CART_EMPTY: "നിങ്ങളുടെ ബാസ്കറ്റ് ശൂന്യമാണ്",
    CART_ADD_PLACEHOLDER: "സാധനങ്ങൾ ചേർക്കുക...",
    PROFILE_TITLE: "ആരോഗ്യ പ്രൊഫൈൽ",
    PROFILE_DESC: "വിവരങ്ങൾ നിയന്ത്രിക്കുക.",
    VOICE_SEARCH_ERROR: "ശബ്ദം തിരിച്ചറിയാനായില്ല, ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    VOICE_SEARCH_HINT: "ശ്രദ്ധിക്കുന്നു...",
    VOICE_OUTPUT_HINT: "വിധി കേൾക്കുക",
    VOICE_PLAYING: "സംസാരിക്കുന്നു...",
  },
  as: {
    NAV_HOME: "হোম",
    NAV_ANALYZE: "সন্ধান",
    NAV_CART: "কাৰ্ট",
    NAV_INSIGHTS: "ইনচাইটচ",
    NAV_PROFILE: "প্ৰফাইল",
    NAV_INBOX: "ইনবক্স",
    NAV_LOGOUT: "লগআউট",
    WELCOME_TITLE: "নিউত্ৰিছাথি AI লৈ স্বাগতম",
    WELCOME_SUBTITLE: "আপোনাৰ ব্যক্তিগত খাদ্য বুদ্ধিমত্তা সংগী।",
    WELCOME_WHAT_LABEL: "নিউত্ৰিছাথি কি?",
    WELCOME_WHAT_DESC: "নিউত্ৰিছাথিয়ে ভাৰতীয় ব্যঞ্জন, স্ন্যাকছ আৰু গোলকীয় ব্ৰেণ্ডসমূহ বিশ্লেষণ কৰি আপোনাক আপোনাৰ আঞ্চলিক খাদ্য সংস্কৃতিৰ ওপৰত ভিত্তি কৰি তাৎক্ষণিক স্বাস্থ্য স্ক’ৰ আৰু স্মাৰ্ট বিকল্প প্ৰদান কৰে।",
    WELCOME_HOW_LABEL: "কেনেকৈ ব্যৱহাৰ কৰিব",
    WELCOME_STEP1: "যিকোনো ডিছ, ব্ৰেণ্ড বা মুদী সামগ্ৰীৰ সন্ধান কৰক।",
    WELCOME_STEP2: "তাৎক্ষণিক স্বাস্থ্য স্ক’ৰ (০-১০০) আৰু বিপদাশংকা মূল্যায়ন লাভ কৰক।",
    WELCOME_STEP3: "সুস্থ হৈ থাকিবলৈ স্মাৰ্ট বিকল্পসমূহ চাওক।",
    WELCOME_EXAMPLES_LABEL: "এই উদাহৰণবোৰ চেষ্টা কৰি চাওক",
    WELCOME_START_BTN: "টেষ্টিং আৰম্ভ কৰক",
    SEARCH_TITLE: "নিউত্ৰিছাথি AI",
    SEARCH_DESC: "আপোনাৰ খাদ্যত কি আছে জানক।",
    SEARCH_PLACEHOLDER: "খাদ্য খোজক...",
    SEARCH_ANALYZE_BTN: "বিশ্লেষণ কৰক",
    SEARCH_HISTORY_LABEL: "শেহতীয়া",
    RESULT_HEALTH_SCORE: "স্বাস্থ্য স্ক’ৰ",
    RESULT_VERDICT: "ৰায়",
    RESULT_DECISION: "সিদ্ধান্ত",
    RESULT_QUANTITY: "সুৰক্ষিত পৰিমাণ",
    RESULT_ALTERNATIVES: "বিকল্প",
    RESULT_REASON: "কাৰণ",
    RESULT_LOGIC: "যুক্তি",
    RESULT_RISK: "সতৰ্কবাণী",
    CART_TITLE: "বাস্কেট অডিট",
    CART_DESC: "তালিকা পৰীক্ষা কৰক।",
    CART_ITEMS_LABEL: "মোৰ বাস্কেট",
    CART_SWAPS_LABEL: "স্মাৰ্ট বিকল্প",
    CART_ANALYZING: "বিশ্লেষণ কৰি থকা হৈছে...",
    CART_AUDIT_BTN: "সম্পূৰ্ণ বাস্কেট অডিট কৰক",
    CART_VERDICT: "ৰায়",
    CART_EMPTY: "আপোনাৰ বাস্কেট খালী",
    CART_ADD_PLACEHOLDER: "সামগ্ৰী যোগ কৰক...",
    PROFILE_TITLE: "স্বাস্থ্য প্ৰফাইল",
    PROFILE_DESC: "তথ্যাদি পৰিচালনা কৰক।",
    VOICE_SEARCH_ERROR: "কণ্ঠ চিনাক্ত কৰিব পৰা নগ'ল, অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।",
    VOICE_SEARCH_HINT: "শুনি আছোঁ...",
    VOICE_OUTPUT_HINT: "ৰায় শুনক",
    VOICE_PLAYING: "কথা কৈ আছোঁ...",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("nutrisaathi_lang") as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("nutrisaathi_lang", lang);
  };

  const t = (key: string) => {
    const currentTranslations = translations[language] || translations["en"];
    return currentTranslations[key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
